

//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  *****
//Auto Generated by UVM-Generator
//Author: beng.jiang
//date: 2022-12-23
//Contents:pwr_ctrl_pkg
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  *****

`ifndef PWR_CTRL_PKG__SV
`define PWR_CTRL_PKG__SV
package pwr_ctrl_pkg;

    import uvm_pkg::*;

    `include "pwr_ctrl_interface.sv"
    `include "pwr_ctrl_driver.sv"
    `include "pwr_ctrl_monitor.sv"
    `include "pwr_ctrl_sequencer.sv"
    `include "pwr_ctrl_agent_cfg.sv"
    `include "pwr_ctrl_agent.sv"

endpackage: pwr_ctrl_pkg
`endif
 