

//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  *****
//Auto Generated by UVM-Generator
//Author: beng.jiang
//date: 2022-12-23
//Contents:pwr_ctrl_agent
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  *****
`ifndef PWR_CTRL_AGENT_SV
`define PWR_CTRL_AGENT_SV
class pwr_ctrl_agent extends uvm_agent;

	`uvm_component_utils(pwr_ctrl_agent)

	//Config	//Interface
	pwr_ctrl_agent_config agt_cfg;
	virtual pwr_ctrl_inf pwr_ctrl_inf;
	
	//TLM 
	uvm_analysis_port#(pwr_ctrl_req) mon_ap;
	
	//Components
	pwr_ctrl_sequencer sqr;
	pwr_ctrl_driver drv;
	pwr_ctrl_monitor mon;
	
	//Constructor Function
	function new(string name="pwr_ctrl_agent",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	
	//Phase Methods
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual task run_phase(uvm_phase phase);
	
	{{method}}
	// Add user method here
	// e.g. task function
	// User method ends
endclass

function void pwr_ctrl_agent::build_phase(uvm_phase phase);
	super.build_phase(phase);
	`uvm_info(get_name(),"Build Phase is Called",UVM_LOW)
	if(!uvm_config_db#(pwr_ctrl_agent_config)::get(this,"","agt_cfg",agt_cfg))
	begin
		`uvm_fatal(get_name(),"Failed Get pwr_ctrl Agent Config")
	end
	if(!uvm_config_db#(virtual pwr_ctrl_interface)::get(this,"","pwr_ctrl_interface",vif))
	begin
		`uvm_fatal(get_name(),"Failed Get Virtual Interfac pwr_ctrl_inf")
	end
	mon=pwr_ctrl_monitor::type_id::create("mon",this);
	if (agt_cfg.is_active==UVM_ACTIVE)
	begin
		sqr=pwr_ctrl_sequencer::type_id::create("sqr",this);
		drv=pwr_ctrl_driver::type_id::create("pwr_ctrl_drv",this);
	end
	
	// Add user build here
	//e.g. TLM build
	// User build ends
endfunction

function void pwr_ctrl_agent::connect_phase(uvm_phase phase);
	super.connect_phase(phase);
	`uvm_info(get_name(),"Connect Phase is Called",UVM_LOW)
	mon.pwr_ctrl_inf=pwr_ctrl_inf;
	mon_ap=pwr_ctrl_mom.mon_ap;
	if (agt_cfg.is_active==UVM_ACTIVE)
	begin
		drv.pwr_ctrl_inf=pwr_ctrl_inf;
		drv.seq_item_port.connect(pwr_ctrl_sqr.seq_item_export);
	end
	// Add user connect here
	//e.g. TLM  interface connect
	// User connect ends
endfunction

task pwr_ctrl_agent::run_phase(uvm_phase phase);
	super.run_phase(phase);
	`uvm_info(get_name(),"Run Phase is Called",UVM_LOW)

    forever begin
        @(negedge mon.vif.rst_n);
	    if(drv.is_active == 1)begin
	        drv.handle_reset(phase);
	    end
        if(sqr != null)begin
            sqr.handle_reset(phase)
        end
        @(posedge mon.vif.rst_n)

	// Add user logic here

	// User logic ends
endtask


`endif



	
	
	 