

//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  *****
//Auto Generated by UVM-Generator
//Author: beng.jiang
//date: 2022-12-23
//Contents:pwr_ctrl_item
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 

class pwr_ctrl_item extends uvm_sequence_item;
	// Add user data here
	//e.g. rand int addr
	// User data ends
	`uvm_object_utils_begin(pwr_ctrl_item)
	// Add user data here
	//e.g. `uvm_field_int
	// User data ends
	`uvm_object_utils_end
	function new(string name="pwr_ctrl_item");
		super.new(name);
	endfunction
	{{method}}
	// Add user method here
	//e.g. implement constarins
	// User method ends	
endclass

 