
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  *****
//Auto Generated by UVM-Generator
//Author: beng.jiang
//date: 2022-12-23
//Contents:pwr_ctrl_agent_cfg
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
`ifndef PWR_CTRL_AGENT_CFG_SV
`define PWR_CTRL_AGENT_CFG_SV

class pwr_ctrl_agent_cfg extends uvm_object;

	uvm_active_passive_enum is_active=UVM_ACTIVE;

	pwr_ctrl_interface vif;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin(pwr_ctrl_agent_cfg)
		`uvm_field_enum(uvm_active_passive_enum,is_active,UVM_ALL_ON)
		// Add user cfg here
		//e.g. `uvm_field_int
		// User cfg ends
	`uvm_object_utils_end
	function new(string name="pwr_ctrl_agent_cfg");
		super.new(name);

		// Add user cfg here
	
		// User new cfg ends

	endfunction

	// Add user method here
	//e.g. function
	// User method ends
endclass

`endif
 