<%
agent_name = attributes['agent_name']
user = attributes['user_name']
date = attributes['date']
agent_upper = attributes['agent_name'].upper()

%>

//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  *****
//Auto Generated by UVM-Generator
//Author: ${user}
//date: ${date}
//Contents:${agent_name}_item
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 

class ${agent_name}_item extends uvm_sequence_item;
	// Add user data here
	//e.g. rand int addr
	// User data ends
	`uvm_object_utils_begin(${agent_name}_item)
	// Add user data here
	//e.g. `uvm_field_int
	// User data ends
	`uvm_object_utils_end
	function new(string name="${agent_name}_item");
		super.new(name);
	endfunction
	{{method}}
	// Add user method here
	//e.g. implement constarins
	// User method ends	
endclass

