<%
agent_name = attributes['agent_name']
user = attributes['user_name']
date = attributes['date']
agent_upper = attributes['agent_name'].upper()

%>
`ifndef $_agent_upper}_SEQUENCER_SV
`define ${agent_upper}_SEQUENCER_SV
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  *****
//Auto Generated by UVM-Generator
//Author: ${user}
//date: ${date}
//Contents:${agent_name}_sequencer
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class ${agent_name}_sequencer extends uvm_sequencer

	`uvm_component_utils(${agent_name}_sequencer)
	//Config
	${agent_name}_sequencer_config sqr_cfg;
	
	//TLM 
	//default seq_item_port

	//Constructor Function
	function new(string name="${agent_name}_sequencer",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	
	//Phase Methods
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual task run_phase(uvm_phase phase);
	
	{{method}}
	// Add user method here
	//e.g. task function
	// User method ends
endclass

`endif